# Generated by Django 5.2.3 on 2025-06-27 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ed_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='AuthenticationSystem.ed_class'),
        ),
        migrations.AlterField(
            model_name='ed_class',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
